### ISSUE TITLE
Is it compatible with Redmine 2.6.3?

### ISSUE THREAD

**Issue by jvmgtd** [dro123/redmine_meeting_room_calendar#14]
Hello,

I'm trying to use your plugin in the referenced version of Redmine. It does not work. I've found the following problems.
* I must create all the configurable (traker, project, ...) items before installing the plugin. Otherwise I cannot access any project (code 500 error). I must configure project, tracker, etc and the install the plugin in order to make it run
* Once installed the plugin configuration page is more complex than the one that appears on the documentation.
* The result of all the operations is something that seems operable but does not work.I can schedule a meeting but the information does not appear on the calendar.

Thanks in advance,

Jordi Vila

**Comment by dro123** [comment]
Hi Jordi,

I haven't had time to keep up with the latest redmine versions and I think the last one I tested this with was 2.4.something. So there's a chance that newer versions are not compatible anymore.
I'm currently not at home, but if you can wait until next week I can see if I can get it back to working on the weekend.

Regarding the additional options that are not documented... I know :-) Same problem as above.

Tobias

**Comment by jvmgtd** [comment]
Hi Tobias,
Thank you very much! Any news?

**Comment by dro123** [comment]
Hi Jordi,

I tested with 2.6.3 and it seems to work for me without any changes. 
Are you sure you followed all the instructions for the installation from the documentation?

Can you perhaps make a screenshot from the plugin configuration page?

Tobias

**Comment by dro123** [comment]
Hi Jordi,

do you happen to use rails >= 4?
I added support for rails >= 4 with commit 79b22553fc4d76fb4aaeb164da8fd4d5bfe850ab and with this redmine 3.0.1 is supported too.

Tobias

**Comment by jvmgtd** [comment]
Hello Tobias,

The configuration of my Redmine is:

Redmine version: 2.6.3-stable
Ruby: 2.1.5-p273
Rails 3.2.21
Meeting room plugin: 2.1.3

On a Centos 6 x86_64 server

Yes, I migrated the plugin on the production environment.

Jordi

**Comment by dro123** [comment]
Hi Jordi,

Is anything in the log files (redmine/logs/production.log) that could give a clue on what's happening? Works for me with redmine 2.6.3 and rails 3.

If you create a entry in the calendar something like this should show up in the logs:
```
Started GET "/meeting_room_calendar/create?key=xxx&project_id=1&author_id=1&assigned_to_id=1&category_id=0&subject=Admin%2C+Redmine&start_date=2015-04-23&due_date=2015-04-23&custom_field_values%5B1%5D=Raum+1&custom_field_values%5B2%5D=15%3A30&custom_field_values%5B3%5D=15%3A45&event_id=0&recur=true&periodtype=1&period=5" for 127.0.0.1 at 2015-04-22 22:19:39 +0200
Processing by MeetingRoomCalendarController#create as */*
  Parameters: {"key"=>"xxx", "project_id"=>"1", "author_id"=>"1", "assigned_to_id"=>"1", "category_id"=>"0", "subject"=>"Admin, Redmine", "start_date"=>"2015-04-23", "due_date"=>"2015-04-23", "custom_field_values"=>{"1"=>"Raum 1", "2"=>"15:30", "3"=>"15:45"}, "event_id"=>"0", "recur"=>"true", "periodtype"=>"1", "period"=>"5"}
  Current user: admin (id=1)
  Rendered plugins/redmine_meeting_room_calendar/app/views/meeting_room_calendar/create.html.erb within layouts/base (0.0ms)
Completed 200 OK in 291.2ms (Views: 14.9ms | ActiveRecord: 117.5ms)
```

if something goes wrong it may look like this:
```
Completed 500 Internal Server Error in 59.9ms

NoMethodError (undefined method `xxx` for #<User:0x0000000238b6f0>):
```

Tobias

**Comment by dro123** [comment]
Should be fixed with:
d1813fb07244dbb4ba4ed06c21aab7df14f7de88
