### ISSUE TITLE
Not able to configure Meeting Room Plugin

### ISSUE THREAD

**Issue by Pandiarajan90** [dro123/redmine_meeting_room_calendar#16]
Hi,

I am indeed to install "Meeting Room Calendar plugin" in following spec.

Environment:
Redmine version 2.3.0.stable
Ruby version 1.8.7 (i686-linux)
Rails version 3.2.13
Environment production
Database adapter MySQL
Redmine plugins:
redmine_meeting_room_calendar 2.1.3

Have installed plugin from this link[[https://github.com/dro123/redmine_meeting_room_calendar]]

This plugin also shows in Administrator/Plugins. When click to configure this plugin it shows

" Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error. "

My production.log

Started GET "/redmine/settings/plugin/redmine_meeting_room_calendar" for 10.10.110.42 at Mon May 18 06:18:39 -0700 2015
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_meeting_room_calendar"}
  Current user: admin (id=1)
  Rendered plugins/redmine_meeting_room_calendar/app/views/meeting_room_calendar/_meeting_room_calendar_settings.html.erb (5.6ms)
  Rendered settings/plugin.html.erb within layouts/admin (7.8ms)
Completed 500 Internal Server Error in 17ms

ActionView::Template::Error (compile error
/usr/local/share/redmine-2.3.0/plugins/redmine_meeting_room_calendar/app/views/meeting_room_calendar/_meeting_room_calendar_settings.html.erb:13: syntax error, unexpected ':', expecting ')'
...sues = CustomField.where(type: 'IssueCustomField')
                              ^
/usr/local/share/redmine-2.3.0/plugins/redmine_meeting_room_calendar/app/views/meeting_room_calendar/_meeting_room_calendar_settings.html.erb:13: syntax error, unexpected ')', expecting kEND
...here(type: 'IssueCustomField')
                              ^):
    10:   <%= select_tag('settings[tracker_id]', options_for_select([['', 0]] + tracker_ids.collect{|c| [c.name, c.id]}, (@settings['tracker_id'] || 0))) %>
    11: </p>
    12:
    13: <%- custom_fields_issues = CustomField.where(type: 'IssueCustomField') %>
    14: <p>
    15:   <%= label_tag('settings[custom_field_id_room]', l(:label_setting_custom_field_id_room)) %>
    16:   <%= select_tag('settings[custom_field_id_room]', options_for_select([['', 0]] + custom_fields_issues.collect{|c| [c.name, c.id]}, (@settings['custom_field_id_room'] || 0))) %>
  app/views/settings/plugin.html.erb:6:in `_app_views_settings_plugin_html_erb___353587851__633168138'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___353587851__633168138'

Please someone help me to rectify this issue..

**Comment by Pandiarajan90** [comment]
![capture](https://cloud.githubusercontent.com/assets/12497016/7697039/61bae12e-fe21-11e4-9304-66121f9f7d88.PNG)
![capture1](https://cloud.githubusercontent.com/assets/12497016/7697040/624ad8d8-fe21-11e4-868e-0dc25a9817e3.PNG)

**Comment by dro123** [comment]
Hi,

sorry for the late replay, I wasn't at home the whole week.
It seems like rails 3.2 doesn't support the "where" with hashes.

I try to fix this on the weekend. If you need a faster solution you can try to update to rails 4.

**Comment by dro123** [comment]
Or revert this commit:
https://github.com/dro123/redmine_meeting_room_calendar/commit/126681b1bc3c03740a05ee2b3fc6d6d5b442dfd2

**Comment by dro123** [comment]
Should be fixed with:
d1813fb07244dbb4ba4ed06c21aab7df14f7de88
