### ISSUE TITLE
Stuck on Loading 

### ISSUE THREAD

**Issue by ElskerDane** [dro123/redmine_meeting_room_calendar#17]
I have finished the setup steps as listed in the README file but when I go to the "Meeting rooms" tab and I choose to "Go to" a specific date, the screen appears to be stuck in loading mode as seen in the attached image.  Do you have any suggestions on how to fix this?  

![redminecalendarerror](https://cloud.githubusercontent.com/assets/12851016/8117395/ca34f0be-1055-11e5-99dd-4aab9ec364db.PNG)

Information about my system:
~ Windows 7 Virtual Machine
~ 64-bit operating system
~ Local connection only
~ PostgreSQL being used as database.
~ Redmine Version 3.0.3
~ Rails 4.2
~ Ruby 2.0.0

**Comment by dro123** [comment]
Hi,

4 questions:
1) Is it working before you choose a date?
2) Did you try with another browser? 
3) On the lower left of the screenshot it says "Error on page". Does it bring any more information if you hover over it or click on it?
4) Does the production.log file of redmine show some errors?

**Comment by ElskerDane** [comment]
Morning!

1) This is what it looks like when I first click the "Meeting rooms" link: 
![redminecalendarerror2](https://cloud.githubusercontent.com/assets/12851016/8130263/08248f68-10df-11e5-8834-bab73f509b5e.PNG)
So I suppose it isn't working then either...

2) I have not tried with another browser; is there one you would recommend besides Internet Explorer?  I am not sure if I can download a different browser onto the VM though.

3)  Here is the full error message:
"
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E)
Timestamp: Fri, 12 Jun 2015 12:47:27 UTC


Message: Object doesn't support this property or method
Line: 22
Char: 11
Code: 0
URI: http://localhost:3000/plugin_assets/redmine_meeting_room_calendar/javascripts/meetingcalendar.js


Message: 'event.type' is null or not an object
Line: 2
Char: 30180
Code: 0
URI: http://localhost:3000/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.1.js


Message: 'event.type' is null or not an object
Line: 2
Char: 30180
Code: 0
URI: http://localhost:3000/javascripts/jquery-1.11.1-ui-1.11.0-ujs-3.1.1.js
"

4)  The production file is HUGE  here is some of it:
"
Migrating to Setup (1)
WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, mail_option, mail_enabled

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, mail_option, mail_enabled

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

WARNING: Can't mass-assign protected attributes for Setup::Permission: controller, action, description, sort

Migrating to IssueMove (2)
WARNING: Can't mass-assign protected attributes for IssueMove::Permission: controller, action, description, sort, mail_option, mail_enabled

Migrating to IssueAddNote (3)
WARNING: Can't mass-assign protected attributes for IssueAddNote::Permission: controller, action, description, sort, mail_option, mail_enabled

Migrating to ExportPdf (4)
WARNING: Can't mass-assign protected attributes for ExportPdf::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

WARNING: Can't mass-assign protected attributes for ExportPdf::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to IssueStartDate (5)
Migrating to CalendarAndActivity (6)
WARNING: Can't mass-assign protected attributes for CalendarAndActivity::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

WARNING: Can't mass-assign protected attributes for CalendarAndActivity::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

WARNING: Can't mass-assign protected attributes for CalendarAndActivity::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to CreateJournals (7)
WARNING: Can't mass-assign protected attributes for CreateJournals::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to CreateUserPreferences (8)
Migrating to AddHideMailPref (9)
Migrating to CreateComments (10)
Migrating to AddNewsCommentsCount (11)
Migrating to AddCommentsPermissions (12)
WARNING: Can't mass-assign protected attributes for AddCommentsPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

WARNING: Can't mass-assign protected attributes for AddCommentsPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to CreateQueries (13)
Migrating to AddQueriesPermissions (14)
WARNING: Can't mass-assign protected attributes for AddQueriesPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to CreateRepositories (15)
Migrating to AddRepositoriesPermissions (16)
WARNING: Can't mass-assign protected attributes for AddRepositoriesPermissions::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for AddRepositoriesPermissions::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for AddRepositoriesPermissions::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for AddRepositoriesPermissions::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for AddRepositoriesPermissions::Permission: controller, action, description, sort, is_public

WARNING: Can't mass-assign protected attributes for AddRepositoriesPermissions::Permission: controller, action, description, sort, is_public

Migrating to CreateSettings (17)
Migrating to SetDocAndFilesNotifications (18)
Migrating to AddIssueStatusPosition (19)
Migrating to AddRolePosition (20)
Migrating to AddTrackerPosition (21)
Migrating to SerializePossiblesValues (22)
Migrating to AddTrackerIsInRoadmap (23)
Migrating to AddRoadmapPermission (24)
WARNING: Can't mass-assign protected attributes for AddRoadmapPermission::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to AddSearchPermission (25)
WARNING: Can't mass-assign protected attributes for AddSearchPermission::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to AddRepositoryLoginAndPassword (26)
Migrating to CreateWikis (27)
Migrating to CreateWikiPages (28)
Migrating to CreateWikiContents (29)
Migrating to AddProjectsFeedsPermissions (30)
WARNING: Can't mass-assign protected attributes for AddProjectsFeedsPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to AddRepositoryRootUrl (31)
Migrating to CreateTimeEntries (32)
Migrating to AddTimelogPermissions (33)
WARNING: Can't mass-assign protected attributes for AddTimelogPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to CreateChangesets (34)
Migrating to CreateChanges (35)
Migrating to AddChangesetCommitDate (36)
Migrating to AddProjectIdentifier (37)
Migrating to AddCustomFieldIsFilter (38)
Migrating to CreateWatchers (39)
Migrating to CreateChangesetsIssues (40)
Migrating to RenameCommentToComments (41)
Migrating to CreateIssueRelations (42)
Migrating to AddRelationsPermissions (43)
WARNING: Can't mass-assign protected attributes for AddRelationsPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

WARNING: Can't mass-assign protected attributes for AddRelationsPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to SetLanguageLengthToFive (44)
Migrating to CreateBoards (45)
Migrating to CreateMessages (46)
Migrating to AddBoardsPermissions (47)
WARNING: Can't mass-assign protected attributes for AddBoardsPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

WARNING: Can't mass-assign protected attributes for AddBoardsPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

WARNING: Can't mass-assign protected attributes for AddBoardsPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to AllowNullVersionEffectiveDate (48)
Migrating to AddWikiDestroyPagePermission (49)
WARNING: Can't mass-assign protected attributes for AddWikiDestroyPagePermission::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to AddWikiAttachmentsPermissions (50)
WARNING: Can't mass-assign protected attributes for AddWikiAttachmentsPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

WARNING: Can't mass-assign protected attributes for AddWikiAttachmentsPermissions::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled

Migrating to AddProjectStatus (51)
Migrating to AddChangesRevision (52)
Migrating to AddChangesBranch (53)
Migrating to AddChangesetsScmid (54)
Migrating to AddRepositoriesType (55)
Migrating to AddRepositoriesChangesPermission (56)
WARNING: Can't mass-assign protected attributes for AddRepositoriesChangesPermission::Permission: controller, action, description, sort, is_public, mail_option, mail_enabled
"

**Comment by dro123** [comment]
Looks like the internet explorer doesn't like the javascript used. Could you try with Firefox or Chrome?

**Comment by ElskerDane** [comment]
Good news, I tried loading Redmine on Firefox and your plugin worked!  Thank you for the help!
