### ISSUE TITLE
Set end date for the meeting room

### ISSUE THREAD

**Issue by aceccarelli** [dro123/redmine_meeting_room_calendar#18]
The scheduling of the meeting room could set an end date. Applies when we will have a meeting with multiple days. For example, an extensive training. In this case you should create only one issue.
This vision should reflect on the calendar.

Thanks!

**Comment by dro123** [comment]
Done:

d1813fb07244dbb4ba4ed06c21aab7df14f7de88

**Comment by aceccarelli** [comment]
Very good!
Thanks
