### ISSUE TITLE
Link to the related issue

### ISSUE THREAD

**Issue by kostyfisik** [dro123/redmine_meeting_room_calendar#21]
Thank you for nice plugin! Sorry for not being able to help with development.

Just a feature proposal - add link to a related issue from a calendar view. This way it would be easy to discuss something before meeting, provide a little bit more detailed list of topics, attach supplementary files related to the meeting, or simply add related issues from a development project hosted in the same redmine instance. It is also also an easy way to add conclusions from the meeting.

**Comment by kostyfisik** [comment]
There is a walk-a-round - default calendar view of the book a meeting project has a link to the issue of the meeting.

**Comment by dro123** [comment]
Done:

d1813fb07244dbb4ba4ed06c21aab7df14f7de88

**Comment by kostyfisik** [comment]
Thank you!
