### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ddk85** [dro123/redmine_meeting_room_calendar#22]
Hi,
Install your plugin. Did 1-3 things from "Setup" section, after trying to access to any project, or when I try to create new one, I receive error:
Redmine. Ошибка 500
undefined method `project_meeting_rooms' for #<Project:0x00000003094568>

And a big log of course. If you need it I can send it to you.

**Comment by dro123** [comment]
Hi,

looks like you didn't actually install the plugin.
Did you run 'rake redmine:plugins:migrate'?

**Comment by ddk85** [comment]
I did:
"rake redmine:plugins:migrate RAILS_ENV=production"
because development ENV didn't configure
after that restart daemon, of course

At "Administration->Plugins" I can manage your plugin.

2015-10-28 21:43 GMT+03:00 Tobias Droste <notifications@github.com>:

**Comment by dro123** [comment]
Ok.

Could you tell me your redmine, ruby and rails version?

And could you check if there's a column named 'project_meeting_rooms' in the 'projects' table in your database?

**Comment by ddk85** [comment]
Redmine version                2.6.3.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  3.2.21

No, there is no column:
mysql> SELECT id, project_meeting_rooms FROM projects LIMIT 1;
ERROR 1054 (42S22): Unknown column 'project_meeting_rooms' in 'field list'

2015-10-28 22:34 GMT+03:00 Tobias Droste <notifications@github.com>:

**Comment by dro123** [comment]
Fixed with 9e153e9ac646355ffaf12f2c417542096adcd560

You have to run `rake redmine:plugins:migrate RAILS_ENV=production` again!

**Comment by ddk85** [comment]
Yes, now it works.
Thank you.

2015-10-29 1:15 GMT+03:00 Tobias Droste <notifications@github.com>:
