### ISSUE TITLE
error: Bad Request

### ISSUE THREAD

**Issue by ddk85** [dro123/redmine_meeting_room_calendar#25]
Hi,
If enter http://redmine/meeting_room_calendar and try to select "All" in "Meeting rooms" I got error:
"error: Bad Request"

Via developer console at firefox I see that it try to access "http://redmine/issues.json" and receive "HTTP/1.1 400 Bad Request"

**Comment by dro123** [comment]
Could you post the complete URL of that request (you can remove the api key and hostname)?

**Comment by ddk85** [comment]
"http://redmine/issues.json" - is the full url, that it try to access.

2015-10-31 4:36 GMT+03:00 Tobias Droste <notifications@github.com>:

**Comment by dro123** [comment]
You have to go to the "Network analysis" tab in the developer console (cstrl+shift+q). There's the complete URL which should look like:
http://<hostname>/redmine/issues.json?key=<apikey>&project_id=8&cf_4=Raum%20A%26R&start_date=%3E%3D2015-10-19&status_id=*&limit=100&offset=100

**Comment by ddk85** [comment]
Sorry.
Here it's:
http://redmine/issues.json?key=&project_id=3&cf_18=room1|room2&start_date=%3E%3D2015-10-19&status_id=*&limit=100&offset=0



2015-11-02 13:50 GMT+03:00 Tobias Droste <notifications@github.com>:

**Comment by ddk85** [comment]
Fixed it.
Redmine API doesn't understand multiple values for one custom field variable (cf_18=room1|room2).
But it seems not necessary in this case.

**Comment by dro123** [comment]
I have to look at this, there was a reason I included that in the query. It works with redmine >= 3.0 but not with your version. I probably split the query in one for each room.

In your setup it's probably enough to just remove cf_18 and add the tracker id.

**Comment by sporteka** [comment]
Hi,
I have the same problem on:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.2-p95 (2014-05-08) [x86_64-linux-gnu]
  Rails version                  4.2.5

I'm not e profi in ruby, and I can't fix cf_ problem- if I sipmle remove it in meetingcalendar.js- nothing happend with or without cf_, or if I change cf_ on track_id.

Please help!

/issues.json?key=43edcc7ff5e191b8d20eadcef62d627513e3a4e9&project_id=29&cf_12=Balt%C4%81%20z%C4%81le|Sarkan%C4%81%20z%C4%81le&start_date=%3E%3D2015-12-09&status_id=*&limit=100&offset=0

**Comment by dro123** [comment]
You have to do this:

https://github.com/ddk85/redmine_meeting_room_calendar/commit/da63036f5ee73801a8ff99179d4ccfbff5bdbac9#diff-c795ed188c5c630ca87ceedb5c638701

but since you're using redmine 3.2.x this shouldn't be a problem. 
Try it this way and report back if this fixes your problem too.

And is this only occurring if you select "All" rooms? Or do you get an error for single rooms too?

**Comment by sporteka** [comment]
Hi,

Thank You! Now it work correctly! 

Before we fix the problem was only for "all" screen.

**Comment by arquio** [comment]
We are using Redmine 2.5.2.stable.15418 and we have the same problem.

> Environment:
>   Redmine version                2.5.2.stable.15418
>   Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
>   Rails version                  3.2.19

```
Building Meetings JSON
meetingcalendar.js?1473679029:685 Reload Calender
Failed to load resource: the server responded with a status of 400 (Bad Request)
/ssues.json?key=0ccd113e5468baf4402ff283e5d21fa54de80360&project_id=291&cf_41=Sala%20C%C3%A9sped|Sala%20Scrum|Sala%20Fondo&start_date=%3E%3D2016-08-29&status_id=*&limit=100&offset=0
```

Some idea?

Thanks!

**Comment by dro123** [comment]
You have to use the patch from 2 comments above: https://github.com/ddk85/redmine_meeting_room_calendar/commit/da63036f5ee73801a8ff99179d4ccfbff5bdbac9#diff-c795ed188c5c630ca87ceedb5c638701

**Comment by dro123** [comment]
Should be fixed now with this commit:
04649f3751447442ab4e4f739d68c6dbffe79723
