### ISSUE TITLE
How can I book any room at all day including all day?

### ISSUE THREAD

**Issue by xp025** [dro123/redmine_meeting_room_calendar#28]
I had tried to change the code for booking at weekend. But it had failed.

I changed the following the prameter in assets/javascripts/meetingcalendar.js
```
weekends : from false to true
```
It only display the all day.

So I had changed in the same file. The changed lines are;
```
jAlert(langWarningWeekend, langInfo);
return false;
```
I commented out them. 
But it doesn't work fine. When I tried the book at Saturday, the dialog of wrong subject appeared.
And then, I commented out 
```
jAlert(langInvalidSubject, langInfo);
return false;
```
My using language is Japanese. When I use the original code, it doesn't appear.

Unfortunatlly, my browser hungd up when I book at Saturday.

How can I book any room at all day including weekend ?

**Comment by dro123** [comment]
Hi,

with 95e5c1ac4d14e3e324a90cc8651d4227c34ac593 there's a new setting in the plugin settings that enables bookings on weekends.

You have to run `rake redmine:plugins:migrate` again after updating the plugin.
