### ISSUE TITLE
Shared booking

### ISSUE THREAD

**Issue by kostyfisik** [dro123/redmine_meeting_room_calendar#29]
Hi!

Thank you for nice plug-in! I have a question. We have several sets of equipment in the same lab room, this way it few peoples can work in the same room simulatiously. This way it is requiered to be able to make a shared (overlapping) booking for the same room. I was able to find isOvelapped function in the code and make it alway to return false. However, mouse drag-and-drop still forbids overlapping of booking for the same room and I was not able to find this condition check.

Coud anyone point me the place in the source code where it is located?

Best regards,
Kostya

**Comment by dro123** [comment]
You have to return true here too:
https://github.com/dro123/redmine_meeting_room_calendar/blob/master/assets/javascripts/meetingcalendar.js#L498
