### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by kay54068** [dro123/redmine_meeting_room_calendar#3]
hi,
i follow you step. get error massage, like ...
![image](https://f.cloud.github.com/assets/3054544/71886/c4a14db8-5ffa-11e2-9eff-8c38ac1d7ee1.png)

do you help me?

**Comment by dro123** [comment]
Is this after this commit:
d1813fb07244dbb4ba4ed06c21aab7df14f7de88

still a problem?
