### ISSUE TITLE
Start of the week

### ISSUE THREAD

**Issue by kostyfisik** [dro123/redmine_meeting_room_calendar#30]
For some reason the plugin does not obay "Start calendar on" day of the week "Display" "Settings" of our Redmine insallation. While it obeys localization settings. Can anyone confirm the issue?

**Comment by dro123** [comment]
Fixed with:

73e0d3db76489e26ec7227fd918b1ba6e09e381b

**Comment by kostyfisik** [comment]
Thank you! Works fine.

**Comment by kostyfisik** [comment]
Sorry for not finding it out along with the "start of the week" issue.   Date and time settings are not governed too. Could you, please, fix it too? 

According to your fix for "start of the week" this needs some of decision making, and I am not a ruby of java programmer. As a walk-a-round I can tweak it in my local copy, however, it is a route to the dark side.

**Comment by dro123** [comment]
Done:
cf57070e27e477d48c07308d89a4e9de43118f61
