### ISSUE TITLE
Plugin not configured correctly! See Administration

### ISSUE THREAD

**Issue by abdennour** [dro123/redmine_meeting_room_calendar#32]
Clicking on the last item (Meeting Rooms )on the navbar , Redmine redirect me to ```/meeting_room_calendar/missing_config``` URI  , and this page shows this error message : 

> Meeting rooms

>   Plugin not configured correctly! See Administration -> Plugins -> Configuration

**Comment by dro123** [comment]
Well did you install and configure it correctly? Could you post a screenshot of the configuration page?
