### ISSUE TITLE
Plugin works only with role Administrator 

### ISSUE THREAD

**Issue by renzoyugi** [dro123/redmine_meeting_room_calendar#36]
Hi,

I have a problem, plugin only works with role administrator but others roles don´t work, the screen stuck on loading.

The project is public, when I navegate it shows message Redmine API

My info Redmine:

Environment:
  Redmine version                          2.1.4.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.8
  Environment                              production
  Database adapter                         Mysql2

PD: Sorry for my English, thanks

**Comment by dro123** [comment]
Did you follow all the relevant installation steps, especially these?
https://github.com/dro123/redmine_meeting_room_calendar#6-configure-redmine

**Comment by renzoyugi** [comment]
Yes, I follow the instructions but it doesn´t work with other roles, it´s very strange

You view images, thanks.

![image](https://cloud.githubusercontent.com/assets/18590577/14878692/6bcedf4e-0d25-11e6-84cf-184a887839c2.png)

![image](https://cloud.githubusercontent.com/assets/18590577/14878726/9e202570-0d25-11e6-8b94-d1035a2ac239.png)

![image](https://cloud.githubusercontent.com/assets/18590577/14878757/c7c5a76a-0d25-11e6-9631-d302d98c813b.png)

![image](https://cloud.githubusercontent.com/assets/18590577/14878773/dd0c0380-0d25-11e6-817c-8090e457d5ea.png)

**Comment by renzoyugi** [comment]
I changed version Redmine 3.2.2, it works, thanks.
