### ISSUE TITLE
Any modification in the meeting_calendar.css stops working redmine after apache restart

### ISSUE THREAD

**Issue by sanyimano** [dro123/redmine_meeting_room_calendar#40]
In the README.md file you mentioned the possibility of modifying the meeting_calendar.css file.
At first I tried to modify black to #00FFFF (cyan) in line 140: in meetin_calendar.css 
.fc-time-grid-event.meeting_room_2 .fc-time
{
    background-color: black;
}
After restarting apache the redmine error page came up. Unfortunately I did not find anything in the log files. All I wanted is to set unique colors to the rooms, as there are 5 rooms at this time.

**Comment by dro123** [comment]
Changing CSS files can not cause redmine errors. 
Are you sure that's the only change you have done? 
And does it start working again if you put back in #00FFFF?

**Comment by dro123** [comment]
You can try running "rake redmine:plugins:migrate" again after changing the CSS files. Though it shouldn't make a difference.

**Comment by sanyimano** [comment]
Good idea! After modifying the css file,  the "rake redmine:plugins:migrate" made it working, without restarting the apache.
Considering the rail mechanism its absolutely correct. The css file is a part of the plugin, so any modification in the plugin files requires the migration.
The output shows, that rake recognized the modification and did the job.
root@meeting:~redmineuser/public_html # rake redmine:plugins:migrate
Migrating project_priority (Project Priority)...
Migrating redmine_base_deface (Redmine Base Deface plugin)...
Migrating redmine_maintenance_mode (Redmine Maintenance Mode)...
Migrating redmine_meeting_room_calendar (Redmine Meeting Room Calendar plugin)..

The next I will try is to select different color for every room.
Thanks a lot!

**Comment by dro123** [comment]
Good :-)
