### ISSUE TITLE
Past meetings go back only 30 days

### ISSUE THREAD

**Issue by nicbagit** [dro123/redmine_meeting_room_calendar#42]
Hi,
Is there a way to increase the length of time we can see past meetings in Calendar view? Is seems to go back only for the last 30 days.
Thanks.

**Comment by dro123** [comment]
https://github.com/dro123/redmine_meeting_room_calendar/blob/master/assets/javascripts/meetingcalendar.js#L41

Change 14 to the number of days you want to go back

**Comment by nicbagit** [comment]
Thanks, is there any need to recompile or reboot after this change?

I am asking because my calendar still does not show the older entries; unless this change does not work retroactively.

**Comment by dro123** [comment]
Yes you have to run rake redmine:plugins:migrate again
