### ISSUE TITLE
Auto close issues related to the past meetings

### ISSUE THREAD

**Issue by kostyfisik** [dro123/redmine_meeting_room_calendar#43]
Motivation: intensive use of the plugin generates a lot of unclosed issues. Users have to close them manually, this is not very convenient.

Probably this can be done every time someone add\changes the calendar.

**Comment by dro123** [comment]
Just set the issue status in the plugin settings to "closed" so that they are closed from the beginning. They will still appear in the calendar but don't bother you otherwise.

**Comment by kostyfisik** [comment]
Seems to be a good way, thanks!
